### ISSUE TITLE
大佬，报错提示： ref  c7a59c9cff8887abb89f2c36b3911f5fbdf189c8 找不到。

### ISSUE THREAD

**Issue by junlandroid** [CarGuo/GSYGithubAppFlutter#464]
首先感谢大佬开源。想问下，pubspec.yaml 文件中 这么配置的原因是什么？虽然运行起来了，但还是想问下。
```
  flare_flutter:
    git:
      url: https://github.com/CarSmallGuo/Flare-Flutter.git
      path: flare_flutter
      ref: c7a59c9cff8887abb89f2c36b3911f5fbdf189c8
```
报错：
1.在未修改yaml 文件的情况下，get packages 时候，报错提示： ref  c7a59c9cff8887abb89f2c36b3911f5fbdf189c8 找不到。大概是这个意思

然后按照官方的改了下yaml ，就好了
```
  flare_flutter:
    git:
      url: git://github.com/2d-inc/Flare-Flutter.git
      ref: dev
      path: flare_flutter
```
-------------------------------------------------
后来，重新改为原来的yaml 。
报错：
Git error. Command: git rev-list --max-count=1 master
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

大佬，还是想问下 ，那样写的好处是啥？
